### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by crazyfox55** [crazyfox55/VotingApplication#11]
Currently everything is manually tested and hopefully exhaustively.

We will need to start looking into automated testing. The link below has some information, I'm not sure how to validate that we are testing exhaustively.
https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/testing

**Comment by colemtg** [comment]
Started implementing basic controller tests. Think I configured it correctly.

**Comment by crazyfox55** [comment]
It looks good so far but there are two separate folders VotingApplicationTests and  VotingApplication.Tests.

**Comment by colemtg** [comment]
Thanks for letting me know, VotingApplicationTests should have been deleted.

**Comment by crazyfox55** [comment]
Selenium testing instead.
