### ISSUE TITLE
Filter by demographics and Add additional demographic info

### ISSUE THREAD

**Issue by crazyfox55** [crazyfox55/VotingApplication#24]
Click voter demographics page, filter by desired demographics

What are some of the filters we should use for each demographic?
***insert list of demographics we track***

What are some interesting graphs of the voter statistics?

**Comment by crazyfox55** [comment]
Login, register to vote, go to profile, click add update information

Should demographics be required before registering to vote is complete?

**Comment by colemtg** [comment]
Added the demographics cshtml and view model on the VotingRegistrationDemographics Branch. Wasn't sure where it should go, currently there is just a link from the user dashboard. I think it should be required to fill out as well before the user can vote.

**Comment by crazyfox55** [comment]
Voter verification is automatically ignored some system should be implemented.
